# -*- coding: utf-8 -*-
"""Lista 4 - 1/9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 1
# Prática 

'''lados = int(input('Digite a quantidade de lados! '))
lado = float(input('Digite a medida do lado! '))
if lados == 3:
# calculo da área do Triangulo
  area = lado ** 2 * 3 ** (1/2) /4 
  print('TRIANGULO')
  print("área: %.2fcm"%area)
# calculo da area do quadrado
elif lados == 4:
  area = lado ** 2
  print('QUADRADO')
  print("área: %.2fcm"%area)
elif lados == 5:
  print('PENTAGONO')'''