# -*- coding: utf-8 -*-
"""exercicio 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 8
'''num = []
valor = int(input('Digite um valor: '))
# usando while para repetir o programa em loop.
while (valor != 0):
  num.append(valor)
# e max para retornar o valor máximo de um número.
  print('Maior valor',max(num))
  valor = int(input('Digite um valor: '))
else:
  print('----')'''