# -*- coding: utf-8 -*-
"""exercicio 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 2
'''lados = int(input('Digite a quantidade de lados! '))
lado = float(input('Digite a medida do lado! '))
if lados == 3:
# calculo para calcular a área de um triangulo
  area = lado ** 2 * 3 ** (1/2) /4 
  print('TRIANGULO')
  print("área: %.2fcm"%area)
elif lados == 4:
# calculo para calcular a area de um quadrado
  area = lado ** 2
  print('QUADRADO')
  print("área: %.2fcm"%area)
elif lados == 5:
  print('PENTAGONO')
# exercicio 2 inserir 'não é um poligono'
elif lados <3:
  print('NÃO É UM POLÍGONO')
#inserir 'poligono não indentificado'
elif lados >5:
  print('POLÍGONO NÃO INDENTIFICADO')'''