# -*- coding: utf-8 -*-
"""exercicio 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 6
'''num = int(input('Digite um número '))
for seguindo in range(num):
# usando loops-for para designar o 0 até o numero Digitado
  print(seguindo)'''