# -*- coding: utf-8 -*-
"""exercicio 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 3 
'''valor1 = int(input('Digite valor 1: '))
valor2 = int(input('Digite valor 2: '))
valor3 = int(input('Digite valor 3: '))
if (valor1 == valor2) or (valor3 == valor1) or (valor2 == valor3):
  print('não repita os números! ')
elif (valor1 > valor2) and (valor1 > valor3):
  print('valor 1 é Maior')
elif (valor2 > valor1) and (valor2 > valor3):
  print('valor 2 é Maior')
else:
  print('valor 3 é Maior')'''