# -*- coding: utf-8 -*-
"""exercicio 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 9
'''valor = int(input('Digite 4 valores: '))
#compondo unidade, dezenan centena e milhar
unid = valor % 10
valor = (valor - unid)/10
dez = valor % 10
valor = (valor - dez)/10
cent = valor % 10
valor = (valor - cent)/10
milh = valor
dez = int(dez)
cent = int(cent)
milh = int(milh)
print('unidade:',unid, 'dezena:',dez, 'centena:',cent, 'milhar:',milh)'''