# -*- coding: utf-8 -*-
"""exercicio 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 4 
'''lado1 = int(input('Digite o valor do lado 1: '))
lado2 = int(input('Digite o valor do lado 2: '))
lado3 = int(input('Digite o valor do lado 3: '))
# Usando if e else para designar o comando.
if (lado1 == lado2) and (lado1 == lado3) :
  print("Triângulo Equilátero")
elif (lado1 == lado2) and (lado1 != lado3) or (lado2 == lado3) and (lado1 != lado2) or (lado1 == lado3) and (lado3 != lado2) :
  print('Triângulo Isóscele')
else:
  print('Triângulo Escaleno')'''
