# -*- coding: utf-8 -*-
"""exercicio 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 5
'''a = float(input('Digite o valor do ângulo a: '))
b = float(input('Digite o valor do ângulo b: '))
c = float(input('Digite o valor do ângulo c: '))
# 90° =  ao angulo reto, atribuindo os angulos em cada um de seus tipos triangulos
if a == 90 or b == 90 or c == 90:
  print('Triângulo Retângulo')
elif a > 90 or b > 90 or c > 90:
  print('Triângulo Obtusângulo')
else:
  print('Triângulo Acutângulo')'''
