# -*- coding: utf-8 -*-
"""exercicio 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14cAhC78faRS5LGUqUDLDy1ZgysOo9hH5
"""

# Diciplina : Probabilidade e Estastistica
# Leonardo Maruno Drews /Turma: A
# Matricula: 20114290095
# Lista 4



# Exercício 7
'''num = int(input('Digite um número de 1 á 4: '))
# usarei while caso se repita de digitar o número não solicitado
while (num <1 or num > 4):
  print('Entrada inválida')
  num = int(input('Digite novamente um número de 1 á 4: '))
else:
  print('Número: ',num)'''